## Intro to Numpy
* Numpy is a powerful libray for storing and manipulating arrays.  
* Numpy is typically what other methods uses under the hood to manipulate matricies


In [3]:
import numpy as np

# create and array
x = np.array(['a', 'b', 'c', 'a'])
print(x)
# each array has a data type (dtype) some version of float, int or object(catagorial)
print(x.dtype)

# numpy supports standard indexing
print('numpy indexing:', x[1], x[2], x[-1])

# numpy also supports boolian indexing
print('booling indexing:', x[x == 'a'])

# numpy supports indexing by other numpy arrays

print('array indexed by arrays', x[np.array([1, 2, 1, 1, 1])])
# numpy has it's many functions for removing nones, nans, and inf
x = np.arange(5)
np.isfinite(1/x)


['a' 'b' 'c' 'a']
<U1
numpy indexing: b c a
booling indexing: ['a' 'a']
array indexed by arrays ['b' 'c' 'b' 'b' 'b']


c:\python36\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


array([False,  True,  True,  True,  True])

In [2]:
## Generating arrays in numpy 
import numpy as np
print('2 x 2 matrix of zeros', np.zeros((2, 2)))
print('2 x 3 matrix of ones', np.ones((2,3)))
print('3 random uniforms', np.random.rand(2))
print('3 random normals', np.random.normal(0, 1, 2))
print('number zero to 10', np.arange(10))




2 x 2 matrix of zeros [[0. 0.]
 [0. 0.]]
2 x 3 matrix of ones [[1. 1. 1.]
 [1. 1. 1.]]
3 random uniforms [0.23431766 0.09885111]
3 random normals [0.80845174 0.38607864]
number zero to 10 [0 1 2 3 4 5 6 7 8 9]


In [14]:
# reshaping and combining arrays is one of the most usefull attributes of numpy
x = np.arange(8)
print('x', x)
print('x reshaped to 2 x 4', np.reshape(x, (2, 4)))
print('x reshaped to 2 x 4', np.reshape(x, (4, 2)))

# ravel with un ravel the matrix 
print('ravel back to 1 d', np.ravel(np.reshape(x, (4, 2))))



x [0 1 2 3 4 5 6 7]
x reshaped to 2 x 4 [[0 1 2 3]
 [4 5 6 7]]
x reshaped to 2 x 4 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
ravel back to 1 d [0 1 2 3 4 5 6 7]


In [10]:
# numpy array data types can causes some strange effects
# in this case, the whole array's dtype is changed to float
x = np.array([1, 2, 3], dtype=int)
x = x + 1.3
print(x)

# in this case, the number is truncated (decimal is removed)
# numpy array data types can trunc numbers if you not carefull
x = np.array([1, 2, 3], dtype=int)
x[1] = 1.3
print(x)


[2.3 3.3 4.3]
[1 1 3]


In [12]:
#  arrays can be vstacked (rowise) using vstack
x = np.arange(8)
x = np.reshape(x, (4, 2))
print('vstack', np.vstack((x,x)))


vstack [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [13]:
#  arrays can be hstacked (columnwise) using hstack
x = np.arange(8)
x = np.reshape(x, (4, 2))
print('hstack', np.hstack((x,x)))



hstack [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [4]:
# value replacement inside arrays
x = np.arange(10)
x[x == 5] = 1111
print('value replacement inside arrays', x)


value replacement inside arrays [   0    1    2    3    4 1111    6    7    8    9]
